@startuml Tasks-Learning
salt
{
  {+
  [<] | My Tasks
  }

  {#
  * Math Homework — Due Today
  * Packing Bag Checklist
  * Practice Piano — 20m
  * Read 10 Pages
  }

  {+
  [Add Task]
  Stars earned: ★★★☆☆
  }
}
@enduml
